my_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "1189"
      port: 5432
      dbname: groceries
      schema: public
      threads: 1